In [191]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [192]:
import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.activations.activations import Sigmoid, Softmax, ReLU, GELU

In [193]:
x = Tensor(np.random.randn(1,5), requires_grad=True)
weight = Tensor(np.random.rand(5,3), requires_grad=True)
bias = Tensor(np.random.randn(3,), requires_grad=True)

y = x @ weight + bias
fn = Sigmoid()
Z = fn(y)
Z.backward()
x.grad, weight.grad, bias.grad, y.grad, Z.grad

(array([[0.16702503, 0.1847495 , 0.25440598, 0.15112197, 0.36975327]],
       dtype=float32),
 array([[-0.03974773, -0.0507222 , -0.01423913],
        [-0.00802161, -0.0102364 , -0.00287364],
        [ 0.36508614,  0.4658875 ,  0.1307876 ],
        [ 0.3421488 ,  0.4366171 ,  0.12257059],
        [-0.18128945, -0.23134398, -0.0649447 ]], dtype=float32),
 array([0.17627436, 0.22494422, 0.06314811], dtype=float32),
 array([[0.17627436, 0.22494422, 0.06314811]], dtype=float32),
 array([[1., 1., 1.]], dtype=float32))

In [194]:
x1 = Tensor(np.random.randn(1,5), requires_grad=True)
weight1 = Tensor(np.random.rand(5,3), requires_grad=True)
bias1 = Tensor(np.random.randn(3,), requires_grad=True)

y1 = x1 @ weight1 + bias1
fn1 = Softmax()
Z1 = fn1(y1)
Z1.backward()
x1.grad, weight1.grad, bias1.grad, y1.grad, Z1.grad

(array([[0.63602126, 0.48714876, 0.40150025, 0.5550873 , 0.5727482 ]],
       dtype=float32),
 array([[ 1.9223671e-03,  9.4865704e-01,  1.1731976e-02],
        [-3.5940058e-04, -1.7735837e-01, -2.1933788e-03],
        [ 3.1652802e-04,  1.5620145e-01,  1.9317325e-03],
        [-3.5061690e-04, -1.7302376e-01, -2.1397728e-03],
        [-4.0967244e-04, -2.0216672e-01, -2.5001818e-03]], dtype=float32),
 array([0.00151581, 0.748027  , 0.0092508 ], dtype=float32),
 array([[0.00151581, 0.748027  , 0.0092508 ]], dtype=float32),
 array([[1., 1., 1.]], dtype=float32))

In [195]:
x2 = Tensor(np.random.randn(1,5), requires_grad=True)
weight2 = Tensor(np.random.rand(5,3), requires_grad=True)
bias2 = Tensor(np.random.randn(3,), requires_grad=True)

y2 = x2 @ weight2 + bias2
fn2 = ReLU()
Z2 = fn2(y2)
Z2.backward()
x2.grad, weight2.grad, bias2.grad, y2.grad, Z2.grad


(array([[0., 0., 0., 0., 0.]], dtype=float32),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[0., 0., 0.]], dtype=float32),
 array([[1., 1., 1.]], dtype=float32))

In [196]:
x3 = Tensor(np.random.randn(1,5), requires_grad=True)
weight3 = Tensor(np.random.rand(5,3), requires_grad=True)
bias3 = Tensor(np.random.randn(3,), requires_grad=True)

y3 = x3 @ weight3 + bias3
fn3 = GELU()
Z3 = fn3(y3)
Z3.backward()
x3.grad, weight3.grad, bias3.grad, y3.grad, Z3.grad


(array([[0.20156571, 0.485451  , 0.53933126, 0.51542985, 0.38058776]],
       dtype=float32),
 array([[-0.87730855,  0.0848358 ,  0.06053137],
        [-0.3588411 ,  0.03469996,  0.02475884],
        [ 1.9901091 , -0.1924437 , -0.1373109 ],
        [-0.76309305,  0.07379116,  0.05265088],
        [-1.2981429 ,  0.12553053,  0.08956754]], dtype=float32),
 array([ 1.0124764 , -0.09790655, -0.06985751], dtype=float32),
 array([[ 1.0124764 , -0.09790655, -0.06985751]], dtype=float32),
 array([[1., 1., 1.]], dtype=float32))