In [1]:
%load_ext autoreload
%autoreload 3

In [2]:
import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.activations.activations import Sigmoid, Softmax, ReLU, GELU

In [3]:
x = Tensor(np.random.randn(1,5), requires_grad=True)
weight = Tensor(np.random.rand(5,3), requires_grad=True)
bias = Tensor(np.random.randn(3,), requires_grad=True)

y = x @ weight + bias
fn = Sigmoid()
Z = fn(y)
Z.backward()
x.grad, weight.grad, bias.grad, y.grad, Z.grad

(array([[0.26638247, 0.1527659 , 0.3169385 , 0.24369752, 0.227022  ]]),
 array([[ 0.17540674,  0.05824788,  0.1061338 ],
        [ 0.39441131,  0.13097343,  0.23864744],
        [ 0.31984111,  0.10621066,  0.19352706],
        [ 0.09678212,  0.03213875,  0.0585602 ],
        [-0.17551895, -0.05828514, -0.10620169]]),
 array([0.23309323, 0.07740402, 0.14103831]),
 array([[0.23309323, 0.07740402, 0.14103831]]),
 array([[1., 1., 1.]], dtype=float32))

In [4]:
x1 = Tensor(np.random.randn(1,5), requires_grad=True)
weight1 = Tensor(np.random.rand(5,3), requires_grad=True)
bias1 = Tensor(np.random.randn(3,), requires_grad=True)

y1 = x1 @ weight1 + bias1
fn1 = Softmax()
Z1 = fn1(y1)
Z1.backward()
x1.grad, weight1.grad, bias1.grad, y1.grad, Z1.grad

(array([[0.12192864, 0.3004732 , 0.07764703, 0.06777531, 0.11517082]]),
 array([[ 0.07444306,  0.52090697,  0.12797207],
        [ 0.00518101,  0.03625352,  0.00890646],
        [ 0.0131493 ,  0.09201076,  0.02260443],
        [ 0.02290414,  0.16026918,  0.03937359],
        [-0.05954159, -0.41663563, -0.10235555]]),
 array([0.04070705, 0.28484301, 0.06997785]),
 array([[0.04070705, 0.28484301, 0.06997785]]),
 array([[1., 1., 1.]], dtype=float32))

In [5]:
x2 = Tensor(np.random.randn(1,5), requires_grad=True)
weight2 = Tensor(np.random.rand(5,3), requires_grad=True)
bias2 = Tensor(np.random.randn(3,), requires_grad=True)

y2 = x2 @ weight2 + bias2
fn2 = ReLU()
Z2 = fn2(y2)
Z2.backward()
x2.grad, weight2.grad, bias2.grad, y2.grad, Z2.grad


(array([[0., 0., 0., 0., 0.]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([0., 0., 0.], dtype=float32),
 array([[0., 0., 0.]], dtype=float32),
 array([[1., 1., 1.]], dtype=float32))

In [6]:
x3 = Tensor(np.random.randn(1,5), requires_grad=True)
weight3 = Tensor(np.random.rand(5,3), requires_grad=True)
bias3 = Tensor(np.random.randn(3,), requires_grad=True)

y3 = x3 @ weight3 + bias3
fn3 = GELU()
Z3 = fn3(y3)
Z3.backward()
x3.grad, weight3.grad, bias3.grad, y3.grad, Z3.grad


(array([[1.47387265, 1.23585416, 1.79962997, 1.72765734, 0.90943154]]),
 array([[ 0.2495379 ,  0.5254514 ,  0.50413449],
        [-0.62003997, -1.3056168 , -1.25264955],
        [ 1.21162848,  2.55132341,  2.44781939],
        [-0.62571927, -1.31757569, -1.26412328],
        [ 0.9725264 ,  2.04784668,  1.96476809]]),
 array([0.50586318, 1.06519498, 1.02198134]),
 array([[0.50586318, 1.06519498, 1.02198134]]),
 array([[1., 1., 1.]], dtype=float32))