In [9]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [10]:
import pytest
import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.activations.activations import (
    Softmax,
    Sigmoid,
    ReLU,
    GELU,
    Tanh
)
from minitorch.losses.losses import MSE, SoftMaxCrossEntropy

In [11]:
np.ones(10, dtype=np.float32).shape

(10,)

In [12]:
x1 = Tensor(np.random.randn(1,5), requires_grad=True)
weight1 = Tensor(np.random.rand(5,5), requires_grad=True)
bias1 = Tensor(np.random.randn(5,), requires_grad=True)

predicted = x1 @ weight1 + bias1
true = Tensor(np.random.randn(1,5), requires_grad=True)

loss_fn = MSE()
loss = loss_fn(predicted, true)
loss.backward()

In [13]:
predicted

Tensor(data=[[-2.4821948   1.56724813 -1.87456964  0.14235128 -2.09083161]], shape=(1, 5), grad_info= True)

In [14]:
x1.grad, weight1.grad, bias1.grad, predicted.grad,loss.grad

(array([[-8.01008992, -6.25992848, -3.66758834, -7.96831248, -2.21674412]]),
 array([[ 5.03903316,  0.8627609 ,  1.09728106,  1.55964308,  7.34613777],
        [ 1.1956644 ,  0.20471635,  0.26036342,  0.37007292,  1.74309538],
        [ 5.54730077,  0.94978423,  1.20795952,  1.71695819,  8.08711401],
        [-2.87679367, -0.49255185, -0.62643986, -0.89040322, -4.1939241 ],
        [-6.45597642, -1.10536364, -1.40582934, -1.99820455, -9.41182381]]),
 array([-3.45361682, -0.59131295, -0.75204671, -1.06893712, -5.03484383]),
 array([[-3.45361682, -0.59131295, -0.75204671, -1.06893712, -5.03484383]]),
 array(1., dtype=float32))

In [15]:
logits = Tensor(np.random.randn(8,5), requires_grad=True)
targets = Tensor(np.random.randint(0,5, size=(8,)))

loss = SoftMaxCrossEntropy()(logits, targets)
loss.backward()

In [16]:
from typing import List


from numpy.typing import NDArray


class Parameter(Tensor):
    #code 
    def __init__(self, data) -> None:
        if isinstance(data, Tensor):
            data = data.data # convert to raw numpy
        else:
            data = data
        super().__init__(data, requires_grad=True)
        
    def zero_grad(self):
        if self.grad is not None:
            self.grad = np.zeros_like(self.data, dtype=np.float32)
        
    def detach(self):
        raise RuntimeError(
            'Cannot detach a parameter. Convert to Tensor first if intentional'
        )
        
    def __repr__(self):
        return (
            f"Parameter(Tensor(data={self.data},\n "
            f"shape={self.shape},\n "
            f"dtype={self.dtype},\n "
            f"requires_grad=True\n "
            )

# def _get_parameters(data):
#     params = []
#     if isinstance(data, Parameter):
#         return [data] 
#     if isinstance(data, dict):
#         for value in data.values(): #calling _get_parameters recursively
#             if isinstance(value, Tensor):
#                 params.extend(_get_parameters(value))
#     if isinstance(data, (list, tuple)):
#         for item in data:
#             params.extend(_get_parameters(item))
#     return params

# params = _get_parameters(loss.__dict__)

In [17]:
x1 = Parameter(x1)
w1 = Parameter(weight1)
b1 = Parameter(bias1)

In [18]:
x1 @ w1 + b1

Tensor(data=[[-2.4821948   1.56724813 -1.87456964  0.14235128 -2.09083161]], shape=(1, 5), grad_info= True)

In [19]:
x1, w1, b1

(Parameter(Tensor(data=[[-1.45905971 -0.34620644 -1.60622937  0.83297998  1.86933778]],
  shape=(1, 5),
  dtype=float64,
  requires_grad=True
  ,
 Parameter(Tensor(data=[[0.67767329 0.06842024 0.90631594 0.30216471 0.91852328]
  [0.66924531 0.99187327 0.78458572 0.1740042  0.5136325 ]
  [0.35663451 0.08222505 0.79964146 0.21858704 0.30830453]
  [0.50611273 0.68428149 0.80971739 0.42449687 0.9440338 ]
  [0.11919191 0.47526333 0.42848492 0.72457377 0.08486998]],
  shape=(5, 5),
  dtype=float64,
  requires_grad=True
  ,
 Parameter(Tensor(data=[-1.33328687  0.68412208 -0.47162575 -0.71350057 -1.02263256],
  shape=(5,),
  dtype=float64,
  requires_grad=True
  )

In [20]:
x1 = Tensor(np.random.randn(1,5), requires_grad=True)
weight1 = Tensor(np.random.rand(5,3), requires_grad=True)
bias1 = Tensor(np.random.randn(3,), requires_grad=True)

y1 = x1 @ weight1 + bias1
fn1 = Softmax()
Z1 = fn1(y1)
Z1.backward()

In [21]:
def tensor(data, requires_grad=True):
    """create a tensor using the Tensor class

    Args:
        data (list,ndarray): data to use to create the tensor
        requires_grad (bool, optional): _description_. Defaults to True.

    Returns:
        Tensor: N-dimension tensor array storing the data
    """
    return Tensor(np.array(data, dtype= np.float32), requires_grad=requires_grad)

In [22]:
def test_add_backward_basic():
    a = tensor([1.0, 2.0])
    b = tensor([3.0, 4.0])
    grad_out = tensor([1.0, 1.0], requires_grad=False)

    fn = AddBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    print(grad_a, grad_b)

    np.testing.assert_allclose(grad_a.data, grad_out.data)
    np.testing.assert_allclose(grad_b.data, grad_out.data)


def test_add_backward_requires_grad_respected():
    a = tensor([1.0, 2.0], requires_grad=False)
    b = tensor([3.0, 4.0], requires_grad=True)
    grad_out = tensor([1.0, 1.0], requires_grad=False)

    fn = AddBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    print(grad_a, grad_b)
    
    test_grad = Tensor(np.zeros_like(a.data))
    
    np.testing.assert_allclose(grad_a.data, test_grad.data)
    np.testing.assert_allclose(grad_b.data, grad_out.data)


def test_add_backward_invalid_input():
    with pytest.raises(AssertionError):
        fn = AddBackward(1, 2)
        fn(tensor(1.0))
        
test_add_backward_basic()
test_add_backward_requires_grad_respected()
test_add_backward_invalid_input()

NameError: name 'AddBackward' is not defined

In [23]:
def test_sub_backward_basic():
    a = tensor([1.0, 2.0])
    b = tensor([3.0, 4.0])
    grad_out = tensor([1.0, 1.0], requires_grad=False)

    fn = SubBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    print(grad_a, grad_b)
    

    np.testing.assert_allclose(grad_a.data, grad_out.data)
    np.testing.assert_allclose(grad_b.data, -grad_out.data)


def test_sub_backward_requires_grad_respected():
    a = tensor([1.0, 2.0], requires_grad=False)
    b = tensor([3.0, 4.0], requires_grad=False)
    grad_out = tensor([1.0, 1.0], requires_grad=False)

    fn = AddBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    test_grad = Tensor(np.zeros_like(a.data))
    print(grad_a, grad_b)
    np.testing.assert_allclose(grad_a.data, test_grad.data)
    np.testing.assert_allclose(grad_b.data, test_grad.data)


def test_add_backward_invalid_input():
    with pytest.raises(AssertionError):
        fn = SubBackward(1, 2)
        fn(tensor(1.0))
   
test_sub_backward_basic()
test_sub_backward_requires_grad_respected()
test_add_backward_invalid_input()

NameError: name 'SubBackward' is not defined

In [ ]:
def test_div_backward_basic():
    a = tensor([6.0, 8.0])
    b = tensor([2.0, 4.0])
    grad_out = tensor([20.0, 16.0], requires_grad=False)

    fn = DivBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    print(grad_a, grad_b)
    
    np.testing.assert_allclose(
        grad_a.data,
        grad_out.data / b.data
    )

    np.testing.assert_allclose(
        grad_b.data,
        -grad_out.data * a.data / (b.data ** 2)
    )


def test_div_backward_requires_grad_respected():
    a = tensor([6.0, 8.0], requires_grad=False)
    b = tensor([2.0, 4.0], requires_grad=True)
    grad_out = tensor([1.0, 1.0], requires_grad=False)

    fn = DivBackward(a, b)
    grad_a, grad_b = fn(grad_out)
    test_grad = Tensor(np.zeros_like(grad_out.data))
    print(grad_a, grad_b)

    np.testing.assert_allclose(grad_a.data, test_grad.data)
    np.testing.assert_allclose(
        grad_b.data,
        -grad_out.data * a.data / (b.data ** 2)
    )
    
test_div_backward_basic()
test_div_backward_requires_grad_respected()

Tensor(data=[10.  4.]) Tensor(data=[-30.  -8.])
Tensor(data=[0. 0.]) Tensor(data=[-1.5 -0.5])


In [ ]:
def test_transpose_backward_basic():
    a = tensor([[6.0, 8.0], [2.0, 4.0]])
    # b = tensor([2.0, 4.0])
    grad_out = tensor([[20.0, 16.0], [18.0, 12.0]], requires_grad=False)

    fn = TransposeBackward(a,0,1)
    grad_a = fn(grad_out)
    test_grad = grad_out.transpose(0,1)
    
    print(grad_a)
    print(test_grad)
    np.testing.assert_allclose(
        grad_a[0].data,
        test_grad.data
    )



test_transpose_backward_basic()

(Tensor(data=[[20. 18.]
 [16. 12.]], shape=(2, 2), grad_info= None),)
Tensor(data=[[20. 18.]
 [16. 12.]])


In [ ]:
Tensor().grad

TypeError: Tensor.__init__() missing 1 required positional argument: 'data'

In [ ]:
def enable_autograd(quiet=False):
    #* GUARD: prevent double patching
    if hasattr(Tensor, '_autograd_enabled'):
        #* silently return the tensor if already enable - no need to warn 
        return 
    
    #*======= STEP 1 : Add gradient infrastructure to tensor ========
    _original_init = Tensor.__init__ # store the original init to extend it

    def gradient_aware_init(self, data, requires_gradient=False):
        """Extend Tensor init to support gradinet tracking"""
        _original_init(self, data)
        self.requires_grad = requires_gradient
        self.grad = None
        
    Tensor.__init__ = gradient_aware_init

In [ ]:
_original_init = Tensor.__init__

In [ ]:
_original_init(self,data)

NameError: name 'self' is not defined