In [67]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[autoreload of minitorch.optimizers.optim failed: Traceback (most recent call last):
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 274, in check
    superreload(m, reload, self.old_objects, self.shell)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 397, in update_generic
    update(a, b)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 330, in update_class
    old_obj = getattr(old, key)
AttributeError: 'types.GenericAlias' object has no attribute '__copy__'. Did you mean: '__bool__'?
]


In [68]:
import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.optimizers.optim import SGD
from minitorch.nn.layers import Linear
from minitorch.losses.losses import MSE

In [69]:
def sgd_unit_test():
    """Test SGD optimizer implemetation"""
    print('Unit Test: SGD Optimizer ....')
    
    #* basic optimizer test
    param = Tensor(np.array([1.0,2.0], dtype=np.float32), requires_grad=True)
    optimizer = SGD([param], lr=0.1)
    param.grad = Tensor(np.array([2.0, 1.0], dtype=np.float32))
    original_data = param.data.copy()
    grad = param.grad.data
    optimizer.step()
    
    expected = original_data - optimizer.learning_rate * grad
    print(expected, param)
    assert np.allclose(expected, param.data)
    assert optimizer.step_count == 1
    print('Basic SGD optimizer works correctly')
    
    # optimizer with momentum test
    param2 = Tensor(np.array([1.0, 2.0]), requires_grad=True)
    optimizer_momentum = SGD([param2], lr=0.1, momentum=0.9)
    param2.grad = Tensor(np.array([2.0, 1.0]))
    original_data = param2.data.copy()
    grad = param2.grad.data
    optimizer_momentum.step()
    
    expected = original_data - optimizer_momentum.learning_rate * grad
    assert np.allclose(expected.data, param2.data)
    assert optimizer_momentum.step_count == 1, f'step count expected to be 1 got {optimizer_momentum.step_count}'
    print('SGD Oprimizer with momentum works correctly ')
    
    # test weight decay
    param3 = Tensor(np.array([1.0, 2.0]), requires_grad=True)
    optimizer_weight_decay = SGD([param3], weight_decay=0.1)
    param3.grad = Tensor(np.array([3.0, 4.0]))
    
    optimizer_weight_decay.step()

    
    expected = param3.data - optimizer_weight_decay.learning_rate * (param3.grad.data + optimizer_weight_decay.weight_decay * param3.data)
    assert np.allclose(expected, param3.data, rtol=0.05)
    print('SGD Optimizer with weight decay works correctly')
    
    print("SGD optimizer works correctly!")

    
if __name__ == '__main__':
    sgd_unit_test()

Unit Test: SGD Optimizer ....
[0.8 1.9] Tensor(data=[0.8 1.9])
Basic SGD optimizer works correctly
SGD Oprimizer with momentum works correctly 
SGD Optimizer with weight decay works correctly
SGD optimizer works correctly!


In [70]:
x = Tensor(np.array([[2.0, 3.0, 4.6,7.0],
                    [4.0,5.0,8.0,10.0],
                    [5.6,7.0, 11.1,1.0],
                    [2.0, 3.0,0.0,-1.0],
                    [4.0,5.0,-2.0, -10.0],
                    [5.6,7.0, 11.9,12.0]]), requires_grad=True)
y = Tensor(np.array([1.0, 2.0, 3.0, 3.0, 4.0,5.0]), requires_grad=True)

weight = Tensor(np.array([0.1, 0.2, 0.3,0.4]), requires_grad=True)
bias = Tensor(np.array([0.0,0.0,0.0,0.0,0.0,0.0]), requires_grad=True)

loss_fn = MSE()
optimizer = SGD([weight, bias],lr=0.001, momentum=0.9, weight_decay=0.01)

for i in range(100):
    y_hat = x @ weight.transpose() + bias
    loss = loss_fn(y_hat, y)
    if i % 10 ==0:
        print(f'Iteration {i}, loss {loss.data}')
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

Iteration 0, loss 23.954233333333338
Iteration 10, loss 5.652311050735574
Iteration 20, loss 0.7633906746555503
Iteration 30, loss 1.0087382635539146
Iteration 40, loss 0.722996016949936
Iteration 50, loss 0.4647438389142266
Iteration 60, loss 0.41371944880977113
Iteration 70, loss 0.3795707374346713
Iteration 80, loss 0.34471157328713914
Iteration 90, loss 0.3204017848418598


In [71]:
linear = Linear(x.shape[1], y.size, bias=True)
loss_fn = MSE()
optimizer = SGD(linear.parameters(), lr=0.001, momentum=0.0, weight_decay=0.0)
# y_hat = x @ weight + bias

for i in range(100):
    y_hat = linear(x)
    loss = loss_fn(y_hat, y)
    if i % 10 == 0:
        print(f'Iteration {i}, Loss: {loss.data}')
        
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

Iteration 0, Loss: 32.32765511781126


TypeError: unsupported operand type(s) for *: 'float' and 'memoryview'

In [ ]:
y_hat = linear(x)
y_hat, y

(Tensor(data=[[0.97563864 1.94016067 2.89643249 2.88165812 3.87789192 4.84892   ]
  [0.93302619 1.92472076 2.91890333 2.94093689 3.84201818 4.80422565]
  [0.98119594 1.96314107 2.94134973 2.93649647 3.92432908 4.90634274]
  [1.01765974 1.99893939 2.97366478 2.95317318 4.00001063 5.00016707]
  [0.99789989 2.01005607 3.02579265 3.03520163 4.01977577 5.02441517]
  [1.07140975 2.10925602 3.15262701 3.14948936 4.2261852  5.28008004]], shape=(6, 6), grad_info= requires_grad=True),
 Tensor(data=[1. 2. 3. 3. 4. 5.], shape=(6,), grad_info= requires_grad=True))