In [554]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


[autoreload of minitorch.optimizers.optim failed: Traceback (most recent call last):
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 274, in check
    superreload(m, reload, self.old_objects, self.shell)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 500, in superreload
    update_generic(old_obj, new_obj)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 397, in update_generic
    update(a, b)
  File "c:\Users\User\Desktop\babytorch\.venv\lib\site-packages\IPython\extensions\autoreload.py", line 330, in update_class
    old_obj = getattr(old, key)
AttributeError: 'types.GenericAlias' object has no attribute '__copy__'. Did you mean: '__bool__'?
]


In [555]:
import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.optimizers.optim import SGD
from minitorch.nn.layers import Linear
from minitorch.losses.losses import MSE

In [556]:
# def sgd_unit_test():
#     """Test SGD optimizer implemetation"""
#     print('Unit Test: SGD Optimizer ....')
    
#     #* basic optimizer test
#     param = Tensor(np.array([1.0,2.0]), requires_grad=True)
#     optimizer = SGD([param], lr=0.1)
#     param.grad = Tensor(np.array([2.0, 1.0]))
#     original_data = param.data.copy()
#     grad = param.grad.data
#     optimizer.step()
    
#     expected = original_data - optimizer.learning_rate * grad
#     assert np.allclose(expected.data, param.data)
#     assert optimizer.step_count == 1
#     print('Basic SGD optimizer works correctly')
    
#     # optimizer with momentum test
#     param2 = Tensor(np.array([1.0, 2.0]), requires_grad=True)
#     optimizer_momentum = SGD([param2], lr=0.1, momentum=0.9)
#     param2.grad = Tensor(np.array([2.0, 1.0]))
#     original_data = param2.data.copy()
#     grad = param2.grad.data
#     optimizer_momentum.step()
    
#     expected = original_data - optimizer_momentum.learning_rate * grad
#     assert np.allclose(expected.data, param2.data)
#     assert optimizer_momentum.step_count == 1, f'step count expected to be 1 got {optimizer_momentum.step_count}'
#     print('SGD Oprimizer with momentum works correctly ')
    
#     # test weight decay
#     param3 = Tensor(np.array([1.0, 2.0]), requires_grad=True)
#     optimizer_weight_decay = SGD([param3], weight_decay=0.1)
#     param3.grad = Tensor(np.array([3.0, 4.0]))
    
#     optimizer_weight_decay.step()

    
#     expected = param3.data - optimizer_weight_decay.learning_rate * (param3.grad.data + optimizer_weight_decay.weight_decay * param3.data)
#     assert np.allclose(expected, param3.data, rtol=0.05)
#     print('SGD Optimizer with weight decay works correctly')
    
#     print("SGD optimizer works correctly!")

    
# if __name__ == '__main__':
#     sgd_unit_test()

In [560]:
x = Tensor(np.array([[2.0, 3.0, 4.6,7.0],
                    [4.0,5.0,8.0,10.0],
                    [5.6,7.0, 11.1,1.0],
                    [2.0, 3.0,0.0,-1.0],
                    [4.0,5.0,-2.0, -10.0],
                    [5.6,7.0, 11.9,12.0]]), requires_grad=True)
y = Tensor(np.array([1.0, 2.0, 3.0, 3.0, 4.0,5.0]), requires_grad=True)

weight = Tensor(np.array([0.1, 0.2, 0.3,0.4]), requires_grad=True)
bias = Tensor(np.array([0.0,0.0,0.0,0.0,0.0,0.0]), requires_grad=True)

loss_fn = MSE()
optimizer = SGD([weight, bias],lr=0.001, momentum=0.9, weight_decay=0.01)

for _ in range(100):
    y_hat = x @ weight.transpose() + bias
    loss = loss_fn(y_hat, y)
    print(loss)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

Tensor(data=23.954233333333338)
Tensor(data=15.597735310885817)
Tensor(data=7.002096707620397)
Tensor(data=4.674105607992263)
Tensor(data=7.856920275163374)
Tensor(data=10.861800131680537)
Tensor(data=9.590031593006357)
Tensor(data=5.204792880398085)
Tensor(data=1.9952152162807464)
Tensor(data=2.5951306918668124)
Tensor(data=5.652310933047676)
Tensor(data=7.742104960162236)
Tensor(data=6.9255978634190685)
Tensor(data=4.26544057419962)
Tensor(data=2.244396178997597)
Tensor(data=2.171373027081428)
Tensor(data=3.220997882883372)
Tensor(data=3.6914656795087937)
Tensor(data=2.8436365020693852)
Tensor(data=1.4482775887802648)
Tensor(data=0.7633906755512504)
Tensor(data=1.2195169528719865)
Tensor(data=2.130818407527852)
Tensor(data=2.523027840893184)
Tensor(data=2.086099568324145)
Tensor(data=1.3256370846635526)
Tensor(data=0.9225704881310016)
Tensor(data=1.059608800820864)
Tensor(data=1.3580346578260494)
Tensor(data=1.363532613326002)
Tensor(data=1.008738277237916)
Tensor(data=0.612812835202

In [561]:
y_hat = x @ weight.transpose() + bias
y_hat,y

(Tensor(data=[1.54121628 2.69091163 3.16726685 2.54906845 4.12011202 4.11599646], shape=(6,), grad_info= requires_grad=True),
 Tensor(data=[1. 2. 3. 3. 4. 5.], shape=(6,), grad_info= requires_grad=True))

In [575]:
linear = Linear(x.shape[1], y.size, bias=True)
print(linear.parameters())
loss_fn = MSE()
optimizer = SGD(linear.parameters(), lr=0.001, momentum=0.0, weight_decay=0.0)
# y_hat = x @ weight + bias

for i in range(10000):
    y_hat = linear(x)
    loss = loss_fn(y_hat, y)
    if i % 1000 == 0:
        print(f'Iteration {i}, Loss: {loss.data}')
        
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

[Parameter(Tensor(data=[[ 2.23806636e-01 -6.93480802e-01  9.10178157e-02 -1.07566191e-01]
 [ 5.59940188e-01  8.15409005e-01  5.30972344e-01 -6.58918537e-01]
 [-1.36516000e-01  5.89493667e-01  5.59638519e-02 -6.84906360e-01]
 [ 9.52927123e-03  6.37203254e-04  1.63910533e-01 -2.23587234e-01]
 [ 2.83096793e-02 -6.66841412e-02  5.32266039e-01 -9.20956129e-01]
 [-1.75106919e-01  2.45199212e-01  2.07321417e-01 -4.20151804e-01]]), 
shape=(6, 4), 
requires_grad=True, Parameter(Tensor(data=[0. 0. 0. 0. 0. 0.]), 
shape=(6,), 
requires_grad=True]
Iteration 0, Loss: 27.90892417440996
Iteration 1000, Loss: 1.0022412320068266
Iteration 2000, Loss: 0.6085088955998402
Iteration 3000, Loss: 0.5379183466297079
Iteration 4000, Loss: 0.5207227383501065
Iteration 5000, Loss: 0.5124181161581789
Iteration 6000, Loss: 0.5056610262479426
Iteration 7000, Loss: 0.49923875739788254
Iteration 8000, Loss: 0.4929500634652341
Iteration 9000, Loss: 0.48676058672209366


In [576]:
linear.parameters()


[Parameter(Tensor(data=[[ 0.48110417 -0.08498195 -0.12175056  0.05646291]
  [ 0.03533075  0.52003867 -0.19993414  0.08994308]
  [-0.22271108  0.98529047 -0.28692736  0.12807139]
  [ 0.12952789  0.72307958 -0.30349317  0.13680977]
  [ 0.19393939  0.94825717 -0.4056149   0.18292036]
  [-0.00521265  1.36971574 -0.4954232   0.22253103]]), 
 shape=(6, 4), 
 requires_grad=True,
 Parameter(Tensor(data=[0. 0. 0. 0. 0. 0.]), 
 shape=(6,), 
 requires_grad=True]

In [567]:
x[0]

Tensor(data=[2.  3.  4.6 7. ], shape=(4,), grad_info= requires_grad=True)