In [1]:
import numpy as np
import PIL.Image as Image
from io import BytesIO

from minitorch.tensor.tensor import Tensor
from minitorch.transform.transform import (
    RandomCrop, RandomFlip,
    Compose, RandomState,
    Normalization)
from minitorch.transform.helpers import ToTensor,to_chw

In [ ]:
image_path = 'C:\\Users\\User\\Pictures\\bunny-1845263_1920.jpg'
img = Image.open(image_path)
image_array = np.array(img)
image = to_chw(image_array)

(1280, 1920, 3)
(3, 1280, 1920)


In [3]:
state = RandomState(seed=42)
flipped_image = RandomFlip(prob=0.5, state=state, axis=-1)(image)
cropped_image = RandomCrop(size=(10,10), padding=2, state=state)(flipped_image)
normalized_image = Normalization(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])(cropped_image)
image_tensor = ToTensor()(normalized_image)

In [ ]:
state = RandomState(seed=42)
transform = Compose(
    [RandomCrop(size=(100,100), padding=0, state=state),
    RandomFlip(prob=0.5),
    Normalization(mean=[0.5, 0.5, 0.5],
                std=[0.5, 0.5, 0.5]),
    ToTensor()]
)

transformed_image = transform(image)

In [13]:
transformed_image

Tensor(data=[[[ 59.  61.  53. ... 123. 105. 117.]
  [ 49.  27.  45. ... 121. 125. 133.]
  [ 49.  25.  51. ... 125. 107. 103.]
  ...
  [353. 307. 213. ...  95. 109.  89.]
  [379. 363. 319. ... 113.  81.  91.]
  [405. 379. 281. ...  91. 107.  75.]]

 [[ 71.  73.  65. ... 163. 149. 163.]
  [ 61.  39.  57. ... 153. 161. 169.]
  [ 61.  37.  63. ... 151. 135. 131.]
  ...
  [265. 227. 147. ... 131. 139. 119.]
  [279. 293. 271. ... 143. 109. 117.]
  [311. 331. 265. ... 121. 135. 101.]]

 [[ 47.  45.  37. ...  89.  57.  59.]
  [ 41.  15.  33. ...  75.  65.  69.]
  [ 41.  17.  43. ...  63.  37.  33.]
  ...
  [167. 129.  61. ...  83.  93.  77.]
  [153. 157. 147. ...  97.  63.  77.]
  [151. 151. 103. ...  75.  89.  61.]]], shape=(3, 100, 100), grad_info= None)