In [150]:
%load_ext autoreload
%autoreload 3

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [151]:
from __future__ import annotations

import numpy as np
from minitorch.tensor.tensor import Tensor
from minitorch.nn.layers import LayerNormalization, BatchNormalization

In [172]:
mask = Tensor.zeros(shape=(5,5))
wei = Tensor.rand(low=0, high=0.99, shape=(5,5))

In [ ]:
Tensor.

Tensor(data=[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]],shape=(5, 5), grad_info= False)